[package]
authors = ["Martin Disch <martindisch@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "oscore-demo"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
panic-itm = "0.4.1"

# this lets us use `cargo fix`
[[bin]]
name = "oscore-demo"
test = false
bench = false

[profile.release]
codegen-units = 1   # better optimizations
debug = true        # symbols are nice and don't increase the size on flash
lto = true          # better optimizations
opt-level = "z"     # optimize for size
