[package]
name = "util"
version = "0.1.0"
authors = ["Martin Disch <martindisch@gmail.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.3"
nb = "0.1.2"

# This is necessary to stop RLS from trying to find tests and complainining
[lib]
test = false
bench = false
